// 20 in-depth guides for /guides/[slug]. Each must be ≥1200 words; Playwright enforces this.

export interface Guide {
  slug: string;
  title: string;
  h1: string;
  description: string;
  metaDescription: string;
  pillar: string; // parent pillar slug for "related" linking
  datePublished: string;
  sections: { heading: string; body: string }[];
  relatedStateSlugs?: string[];
}

export const guides: Guide[] = [
  {
    slug: 'how-net-metering-works-2026',
    title: 'How net metering works in 2026',
    h1: 'How net metering works in 2026 — and what replaced it where',
    description: 'What net metering is, how it affects your monthly bill, and why several states have moved to "successor tariffs" with different math.',
    metaDescription: 'Net metering in plain English. How you get credited for exports, how successor tariffs differ, and what to ask your installer.',
    pillar: 'incentives-and-tax-credits',
    datePublished: '2026-05-12',
    sections: [
      { heading: 'What "net metering" actually means', body: 'When your home solar system produces more electricity than you are using at that moment, the excess flows out to the grid. Net metering is the billing mechanism that credits you for those exports. On a traditional net-metered bill, your monthly usage is the net of what you imported minus what you exported. If you produced more than you used in a given billing period, your bill credits roll over month to month (and, in some states, are paid out at the end of a yearly true-up cycle at a specific rate).' },
      { heading: 'Why some states replaced net metering', body: 'Utilities argued that full retail-rate net metering forced non-solar customers to subsidize solar customers because exported solar was credited at the same rate the utility would charge for retail power. Whether or not you agree with that framing, the result has been tariff revisions in California (NEM 2.0 to NEM 3.0), Nevada, Arizona, and several other states. Successor tariffs typically value exports at less than the full retail rate and add fixed monthly grid charges for solar customers.' },
      { heading: 'How to read a successor tariff', body: 'If you live in a state with a successor tariff, your quote and your bill will look different. Ask your installer (and your utility) for: the per-kWh export rate, the monthly fixed charge for solar customers, whether the rate changes seasonally or by time-of-use period, how credits roll over month to month, and what happens to unused credits at the annual true-up.' },
      { heading: 'How batteries interact with export credits', body: 'Batteries let you store solar production that would have been exported, then use it during the utility\'s evening peak when time-of-use rates are highest. If your utility pays less than retail for exports, a battery can still pay back over time by increasing the value of every kWh you generate. The actual payback depends on the rate spread, the battery\'s round-trip efficiency, and the battery\'s capital cost.' },
      { heading: 'What to ask your installer', body: 'Ask them to model your first-year and five-year bill savings using your utility\'s current tariff — not a made-up rate escalation. Ask them whether you should consider a battery at install time. Ask whether the system is sized for your current usage or your projected usage (electrification adds load, which can change the math). And ask to see your interconnection agreement terms in writing.' },
      { heading: 'Where to look up your state-specific tariff', body: 'Your utility\'s filed tariff on your state public utilities commission website is the canonical source. Your state energy office website often has program summaries as well. Your installer should also be able to point you at the relevant documents. Avoid relying on a third-party marketing summary as your sole reference — these programs change frequently and outdated summaries are common.' },
    ],
    relatedStateSlugs: ['california', 'arizona', 'nevada', 'hawaii', 'texas', 'florida', 'new-york'],
  },
  {
    slug: 'how-to-read-a-solar-quote',
    title: 'How to read a solar quote',
    h1: 'How to read a solar quote without being misled',
    description: 'Every line of a residential solar proposal — system size, $/W, projected production, financing assumptions — and how to verify each.',
    metaDescription: 'A line-by-line decoder for residential solar proposals. What each number means, how to normalize between quotes, and what to flag.',
    pillar: 'going-solar',
    datePublished: '2026-04-22',
    sections: [
      { heading: 'System size (kW) and number of panels', body: 'System size is the panel rating in kilowatts (sum of panel nameplate watts divided by 1,000). A 5 kW system might be 12 panels at ~415 W each. The size of the system should roughly match your annual electricity consumption in kWh divided by a regional production factor (around 1,200–1,500 kWh per installed kW depending on location).' },
      { heading: 'Projected annual production (kWh)', body: 'This is what your system is expected to produce year one. For two quotes on the same roof to be meaningfully different, one of them has mis-modeled the production. Common under-modeling: unrealistic shading assumptions (zero shading), inflated weather data, or inverter clipping ignored.' },
      { heading: 'Cost per watt ($/W)', body: 'Divide gross cost by system size in watts. $/W is the cleanest way to compare two solar bids ignoring financing. A residential system in the U.S. in 2026 typically runs roughly $2.50 to $4.00+/W before incentives, varying by region and equipment selection.' },
      { heading: 'Equipment list', body: 'Every quote should specify the panel make and model, the inverter make and model, the racking system, and any other equipment (monitoring, battery if included, rapid shutdown initiator). Make sure the equipment on the quote matches what the installer installs — get this in writing in the contract.' },
      { heading: 'Financing terms', body: 'If you finance, the loan term, interest rate (APR), fees, and any prepayment penalties are part of the total cost. A lower-priced system on a high-APR loan can cost more over the loan\'s life than a higher-priced system paid in cash.' },
      { heading: 'Warranty terms', body: 'Three warranties matter: panel product (defects) and performance (degradation), inverter warranty, and installer workmanship warranty. Read all three. Confirm whether the warranties are pro-rated, transferable to a new homeowner, and named in the contract.' },
      { heading: 'Inflation assumptions on bill savings', body: 'Solar proposals typically assume your utility rate rises at 3%–5% per year. Those assumptions drive the savings projection. If the rate rises less (or electricity rates fall), savings will be lower. Ask your installer to show you the sensitivity at 0%, 3%, and 5% utility rate inflation.' },
      { heading: 'Production guarantees', body: 'Some installers offer a production guarantee — they commit to a minimum output and compensate you (in cash, credit, or system repair) if actual output falls short. Production guarantees are valuable but read the trigger carefully: many only apply to equipment failures, not to actual production shortfall.' },
      { heading: 'Red flags in quotes', body: 'High-pressure sales tactics, claims that you must act today for a price, "free solar" claims without a clear explanation (usually refers to a lease or PPA), and quotes that refuse to show itemized equipment are all reasons to slow down.' },
    ],
  },
  {
    slug: 'monocrystalline-vs-polycrystalline-vs-thin-film',
    title: 'Monocrystalline vs polycrystalline vs thin-film',
    h1: 'Monocrystalline vs polycrystalline vs thin-film — what actually differs',
    description: 'The honest technical comparison: efficiency, temperature behavior, cost, and what it means for your home system.',
    metaDescription: 'A practical comparison of monocrystalline, polycrystalline, and thin-film solar panels for residential use. What actually changes for your roof.',
    pillar: 'panels-and-equipment',
    datePublished: '2026-04-15',
    sections: [
      { heading: 'What the three categories mean', body: 'Monocrystalline silicon panels are made from a single (mono) crystal of silicon. Polycrystalline silicon panels are made from many crystals fused together. Thin-film panels are not crystalline silicon at all — they are made by depositing a thin semiconductor layer on a substrate. All three produce electricity from sunlight, but with different efficiency, cost, and behavior characteristics.' },
      { heading: 'Efficiency and space', body: 'Monocrystalline panels are the most efficient of the three at roughly 19%–23% module efficiency in 2026, depending on cell architecture (PERC, TOPCon, HJT, back-contact). Polycrystalline typically runs 15%–17%. Thin-film is around 10%–13%. Higher efficiency means more power per square foot of roof — important if you have a small or unusually shaped roof.' },
      { heading: 'Temperature coefficient', body: 'Panels lose efficiency as temperature rises above 25°C. Monocrystalline panels have a temperature coefficient around -0.30%/°C to -0.40%/°C. Polycrystalline is similar. Thin-film (especially CdTe) tolerates heat better and is sometimes preferred in very hot climates. The effect is real but rarely the dominant variable in a U.S. residential install.' },
      { heading: 'Cost and availability', body: 'Polycrystalline is the cheapest per panel and is widely available. Monocrystalline is more expensive per panel but produces more electricity per panel, so the cost-per-watt is often similar in practice. Thin-film is a niche residential product in 2026 in the U.S., with most installations using monocrystalline silicon.' },
      { heading: 'What this means for your home', body: 'For most U.S. residential roofs, the choice is monocrystalline silicon in some form. Differences within monocrystalline (TOPCon vs HJT vs back-contact) matter to the panel manufacturer\'s engineers but rarely change your roof economics meaningfully. Trust your installer to pick a panel in your budget tier from a reputable manufacturer with a strong warranty.' },
      { heading: 'Aesthetics', body: 'All-black monocrystalline panels are the most common residential aesthetic. Polycrystalline panels often have a slightly speckled blue appearance. Black-on-black and silver-frame options exist across categories. Aesthetics matter to many homeowners — talk to your installer about panel appearance during the design phase.' },
    ],
  },
  {
    slug: 'stc-vs-ptc-ratings',
    title: 'STC vs PTC ratings',
    h1: 'STC vs PTC ratings — what the numbers on a panel mean',
    description: 'STC is the panel\'s nameplate wattage. PTC is closer to what you actually get. Why both exist and when each applies.',
    metaDescription: 'STC vs PTC explained. Standard Test Conditions versus PVUSA Test Conditions — what each measures and why both matter.',
    pillar: 'panels-and-equipment',
    datePublished: '2026-04-08',
    sections: [
      { heading: 'STC: Standard Test Conditions', body: 'STC stands for Standard Test Conditions. A panel rated 415W STC was tested in a lab at 1,000 W/m² of irradiance, 25°C cell temperature, and an air mass of 1.5. STC is the industry standard for naming panel wattage and is what you see on the panel datasheet.' },
      { heading: 'PTC: PVUSA Test Conditions', body: 'PTC stands for PVUSA Test Conditions. PTC was developed to better match real-world performance. It uses 1,000 W/m² irradiance, 20°C ambient temperature, and a wind speed of 1 m/s. PTC typically shows a panel producing around 88%–92% of its STC rating — closer to actual field output.' },
      { heading: 'Why STC is still the standard', body: 'Manufacturers name panels in STC because it is a controlled, reproducible lab test. Every panel is rated the same way. PTC was meant to be a more realistic comparator but never fully displaced STC in the U.S. market. California\'s CSI program historically used PTC ratings for performance-based incentives.' },
      { heading: 'How to think about output', body: 'For a rough rule of thumb, expect around 80%–90% of nameplate STC in real-world conditions for a well-designed system. The figure comes from inverter efficiency losses, temperature, soiling, wiring, and shading. Your installer\'s modeled first-year production should be in this range when normalized for your location.' },
      { heading: 'When STC vs PTC actually matters to you', body: 'Mostly when comparing two panels by the same manufacturer, or when calculating inverter stringing. Inverter datasheets list maximum DC voltage and maximum short-circuit current ratings — both are typically STC. For everyday homeowner decisions, STC is what your installer uses to size the system and your quote should show projected kWh using your location\'s weather data, not a STC-derived multiplication.' },
      { heading: 'Where to look up PTC ratings', body: 'The PVUSA / CEC list historically lists PTC values for installed modules. The California Energy Commission (CEC) maintains a similar list. PVsyst and other modeling tools can also calculate PTC-equivalent ratings. For most homeowner decisions, your installer\'s modeled annual production is what matters — STC and PTC are inputs to that model.' },
    ],
  },
  {
    slug: 'solar-and-ev-charging',
    title: 'Solar and EV charging',
    h1: 'Pairing rooftop solar with an EV at home',
    description: 'How to size solar to charge an EV, what a Level 2 charger adds to your electrical panel, and how time-of-use rates change the math.',
    metaDescription: 'Adding an EV to a solar home: panel math, panel upgrades, Level 2 chargers, and how time-of-use rates affect charging decisions.',
    pillar: 'going-solar',
    datePublished: '2026-04-01',
    sections: [
      { heading: 'How much electricity does an EV use', body: 'A typical U.S. EV uses about 0.30–0.40 kWh per mile. Drive 12,000 miles per year and you add roughly 3,600–4,800 kWh/year to your home electricity use. The exact figure depends on the EV\'s efficiency, your driving, and your climate (cold weather reduces efficiency).' },
      { heading: 'Sizing solar to cover an EV', body: 'If your current solar system is sized to your existing electricity bill, adding an EV will push you into importing from the grid unless you sized with future electrification in mind. A common rule: if you\'re considering an EV in the next few years, size your solar with headroom. Talk to your installer about right-sizing now versus adding later.' },
      { heading: 'Level 2 chargers and electrical panels', body: 'Most EV owners install a Level 2 charger (240V, 30–50 amp circuit). Most U.S. homes already have 200-amp service, which can usually accommodate a Level 2 charger. Some homes will need a panel upgrade. Adding a panel upgrade to a solar install is often cheaper than doing it separately.' },
      { heading: 'Time-of-use charging', body: 'If you are on a time-of-use rate, charging during off-peak hours minimizes grid imports. Solar production during the day plus off-peak charging overnight covers a typical daily commute. Some utilities and apps let you schedule charging to start automatically at off-peak times.' },
      { heading: 'Bidirectional charging', body: 'Vehicle-to-home (V2H) and vehicle-to-grid (V2G) capability is growing. Some EVs and chargers can discharge from the car\'s battery to power your home during an outage or to export to the grid during utility events. V2H/V2G is currently limited by vehicle support, charger compatibility, and utility program availability.' },
      { heading: 'Putting it together', body: 'A solar + EV home is one of the cleanest personal transportation setups. The actual savings depend on your gasoline costs you\'re replacing, your solar production, your electricity rate schedule, and your driving distance. There is no single "payback period" that applies universally.' },
    ],
  },
  {
    slug: 'solar-and-heat-pump',
    title: 'Solar and a heat pump',
    h1: 'Heat pumps, heat pump water heaters, and how they interact with solar',
    description: 'How electrification of heating interacts with rooftop solar production and what to consider if you\'re electrifying heat.',
    metaDescription: 'How heat pumps and heat pump water heaters change your home electricity load — and how to size solar to cover them.',
    pillar: 'going-solar',
    datePublished: '2026-03-22',
    sections: [
      { heading: 'What electrification changes', body: 'Replacing a fossil-fuel furnace, boiler, or water heater with an electric heat pump changes your home\'s electricity load profile significantly. A heat pump is more efficient than resistance electric heating (typically 2.5–4x), but it still uses more electricity than a gas furnace. The right time to think about this is before you sign a solar contract.' },
      { heading: 'Heat pump HVAC load', body: 'A typical U.S. home with a heat pump uses 3,000–7,000 kWh per year for heating and cooling combined. In mild climates the heating load is much smaller; in cold climates it is much larger. Your installer should ask whether you plan to electrify heating in the next several years. If yes, size the system with that in mind.' },
      { heading: 'Heat pump water heaters', body: 'A heat pump water heater uses roughly half the electricity of a resistance water heater. Typical annual use is around 2,500–3,500 kWh. In a garage or basement, the waste heat from the heat pump can be a slight space-heating bonus in winter.' },
      { heading: 'Sizing the full system', body: 'If you are electrifying everything — heating, cooling, water heating, cooking, transportation — your home\'s electricity bill grows substantially. A right-sized solar system for the all-electric home typically runs larger than the typical grid-only home. Talk to your installer about right-sizing from the start.' },
      { heading: 'Battery storage and resilience', body: 'Heat pumps and battery storage pair especially well during grid outages: a heat pump keeps indoor temperatures safe (especially with cold-climate heat pumps), and a battery can run the heat pump for limited periods during an outage. Talk to your installer and your heat pump contractor about the sizing interaction.' },
      { heading: 'Incentives for electrification', body: 'The federal Inflation Reduction Act created incentives for some heat pump installations and related electrification. Verify current rules with a tax professional and the IRS website — these programs have specific eligibility requirements and have been updated since their initial passage.' },
    ],
  },
  {
    slug: 'what-is-an-srec',
    title: 'What is an SREC?',
    h1: 'What an SREC (Solar Renewable Energy Credit) is',
    description: 'SRECs are tradable environmental attributes of solar generation. Some states run SREC markets for residential solar that pay you for every MWh you produce.',
    metaDescription: 'SRECs explained — what they are, how the markets work, and which states still have residential SREC programs in 2026.',
    pillar: 'incentives-and-tax-credits',
    datePublished: '2026-03-12',
    sections: [
      { heading: 'What an SREC represents', body: 'An SREC represents the environmental attributes of one megawatt-hour of solar electricity. SRECs exist because state Renewable Portfolio Standards require utilities to source a certain percentage of their electricity from renewables. Utilities can meet those obligations by buying SRECs from solar generators — including homeowners.' },
      { heading: 'How SREC markets work', body: 'In states with active SREC markets, your system registers with the state program, and an SREC is generated for every MWh (1,000 kWh) your system produces. Those SRECs are sold into the market, with proceeds typically split between you, your installer, and a third-party broker depending on your contract. SREC prices move with supply and demand.' },
      { heading: 'Which states still have active residential SREC markets in 2026', body: 'Active residential SREC markets have narrowed over time. As of 2026, Massachusetts, New Jersey (transitioning to SuSI), Maryland (with periodic SREC-II block structures), and a few others maintain varying residential SREC structures. Verify current status with your state\'s energy office — funding and program structures change.' },
      { heading: 'SREC vs the federal tax credit', body: 'SRECs are different from the federal Residential Clean Energy Credit. They are state-administered, market-priced environmental attributes. You can claim the federal credit (if eligible) AND earn SRECs separately — but always verify eligibility and paperwork with a tax professional.' },
      { heading: 'How to maximize SREC value', body: 'Maximize production (right-size your system, keep panels clean, monitor). Make sure the system is registered with the state program promptly. Track your SREC production through your monitoring app. Avoid long-term contracts that lock in a low SREC price if market prices rise.' },
      { heading: 'SREC contract pitfalls', body: 'Some installers offer a low upfront price in exchange for keeping the SRECs for many years. Read the contract carefully: how long is the SREC assignment, what is the price, what happens if the SREC market collapses, can you keep some of the SRECs. Your state energy office website is the authoritative source for current SREC program terms.' },
    ],
  },
  {
    slug: 'does-solar-raise-property-taxes',
    title: 'Does adding solar raise property taxes?',
    h1: 'Property taxes and rooftop solar — what changes and what doesn\'t',
    description: 'Most U.S. states have property tax exemptions for residential solar, but the rules and the limits vary by state.',
    metaDescription: 'Do solar panels raise your property tax bill? Most states exempt residential solar — here is how to confirm yours does too.',
    pillar: 'incentives-and-tax-credits',
    datePublished: '2026-03-04',
    sections: [
      { heading: 'How property tax treats home improvements', body: 'In most U.S. jurisdictions, a home improvement that increases the value of your home can also increase your assessed property value and therefore your tax bill. A traditional kitchen remodel might add $30,000 of value and add several hundred dollars a year to your property tax bill. Solar historically was treated the same way — until states started carving out exemptions.' },
      { heading: 'State property tax exemptions for solar', body: 'Many U.S. states have enacted property tax exemptions specifically for residential solar. The exact mechanics differ: some exempt the full appraised value of the system, others cap the exemption at a percentage, others exempt for a fixed number of years. Check your county assessor\'s website or your state\'s department of revenue for current treatment.' },
      { heading: 'The typical homeowner experience', body: 'In states with exemptions, the assessed value of your home goes up only by the value of the property without the solar, not the value as improved by solar. The exemption effectively removes the solar value from the property tax base. Talk to your county assessor if you want to confirm treatment before signing a solar contract.' },
      { heading: 'What about home insurance?', body: 'Most homeowner insurance policies cover rooftop solar as part of your dwelling coverage, but you may need to add a rider or increase your dwelling limit. Tell your insurer about the solar install and ask whether the panel system is covered for damage (including weather-related damage) and whether your dwelling limit is adequate.' },
      { heading: 'Solar and resale value', body: 'Homes with owned solar systems typically appraise at a small premium relative to comparable non-solar homes, and that premium is at least loosely aligned with the cost of the system. Leased systems do not always transfer cleanly to a new buyer — if you plan to sell, check the contract terms in advance.' },
      { heading: 'Steps to take', body: 'Before signing: (1) confirm your state\'s residential solar property tax exemption; (2) tell your homeowner insurer; (3) ask your county assessor for an informal review. After install: keep all your documentation, including the property tax exemption filing if your state requires it.' },
    ],
  },
  {
    slug: 'home-insurance-and-solar',
    title: 'Insurance for rooftop solar',
    h1: 'Insurance for rooftop solar — what to confirm with your insurer',
    description: 'How homeowner policies typically cover rooftop solar, what to add to your coverage, and what to ask before installing.',
    metaDescription: 'How homeowner insurance treats rooftop solar panels, what to confirm about coverage, and what to ask before and after install.',
    pillar: 'going-solar',
    datePublished: '2026-02-22',
    sections: [
      { heading: 'Coverage basics', body: 'Most U.S. homeowner insurance policies cover rooftop solar under your dwelling coverage (Coverage A). Some policies require you to specifically schedule the solar system or increase your dwelling limit. If your installer does not help with the insurance conversation, call your insurer directly.' },
      { heading: 'What is typically covered', body: 'Damage from storms, hail, fire, wind, falling trees, and certain other causes listed in your policy is typically covered. Theft of panels and electrical damage from grid events (e.g., surges) may or may not be covered. Read your policy or ask your insurer for the specific terms.' },
      { heading: 'Panel performance warranty vs insurance', body: 'These are different things. The panel performance warranty is between you and the manufacturer (or installer) — it covers failure to produce rated output over time. Insurance covers physical damage from covered perils. Both matter, and they are not substitutes for each other.' },
      { heading: 'Dwelling limit and replacement cost', body: 'A typical U.S. residential solar system costs thousands to install. Your dwelling limit (Coverage A) should cover the full replacement cost of your home including the solar system. If you have an older policy with a replacement-cost basis that\'s too low, increase it before installing solar.' },
      { heading: 'Deductibles and exclusions', body: 'Standard homeowner deductibles apply. Some policies exclude certain perils (earthquake, flood) that would require separate policies. Talk to your insurer about any updates you might need, particularly if you are in a hurricane, wildfire, or hail-prone region.' },
      { heading: 'What to ask before install', body: 'Tell your insurer about the planned install. Ask whether your dwelling limit needs to be increased. Ask whether the policy automatically covers rooftop solar or requires a rider. Ask what your deductible is for damage. Ask for any written confirmation and keep it with your installation paperwork.' },
    ],
  },
  {
    slug: 'hoa-and-solar-rules-by-state',
    title: 'HOA rules for solar by state',
    h1: 'HOA rules for rooftop solar — what state law protects',
    description: 'Many states have laws limiting HOA restrictions on residential solar. The details vary and the practical effect on your install can be significant.',
    metaDescription: 'How state solar rights laws interact with HOA rules, and how to navigate a solar install in a homeowners\' association community.',
    pillar: 'incentives-and-tax-credits',
    datePublished: '2026-02-12',
    sections: [
      { heading: 'Why HOA rules sometimes come up', body: 'Solar panels have to go somewhere visible. Many U.S. neighborhoods are governed by homeowner associations with architectural review and design restrictions. Those restrictions sometimes limit where panels can be placed, what they can look like, and what approvals are needed.' },
      { heading: 'State-level solar access laws', body: 'Many states have enacted "solar access" laws that limit an HOA\'s ability to prohibit residential solar. Typical provisions: the HOA cannot block solar outright; the HOA can require reasonable aesthetic placement (e.g., not facing the street if an alternative is feasible); the HOA can require screening for ground-mount systems. The exact language matters a great deal — Florida\'s solar rights law is unusually strong, while states like Texas limit HOA restrictions primarily for solar easements.' },
      { heading: 'What this means in practice', body: 'Even in states with strong solar access laws, an HOA can sometimes delay or complicate approval. In states without such laws, an HOA may be able to block rooftop solar entirely. If you live in an HOA community, ask your installer about your state\'s solar access law and your HOA\'s architectural rules before signing a contract.' },
      { heading: 'How to navigate an HOA', body: 'Step 1: review your HOA\'s CC&Rs (covenants, conditions, and restrictions). Step 2: ask your installer for a sample HOA submission package — most experienced installers have one. Step 3: present the package to the architectural review board with the state solar access law cited if relevant. Step 4: keep documentation in case you need to escalate.' },
      { heading: 'When to push back', body: 'If your HOA prohibits solar in violation of state law, escalate — typically to a state attorney general\'s office or a private attorney specializing in solar access. There are nonprofit organizations that help homeowners in this situation; their resources are generally free and worth using.' },
      { heading: 'What you can do', body: 'Before buying a home in an HOA community, check the CC&Rs for solar. Before signing a solar contract, get HOA approval in writing. After install, keep all approvals and the CC&Rs as part of your home records.' },
    ],
  },
  {
    slug: 'string-vs-microinverter-vs-optimizer',
    title: 'String inverter vs microinverter vs power optimizer',
    h1: 'String inverter vs microinverter vs power optimizer — the real differences',
    description: 'Three inverter topologies, what makes each one appropriate, and how to choose when your installer recommends a specific configuration.',
    metaDescription: 'String vs microinverter vs power optimizer — the residential solar inverter topologies compared on cost, monitoring, shade performance, and reliability.',
    pillar: 'panels-and-equipment',
    datePublished: '2026-02-04',
    sections: [
      { heading: 'What the three topologies are', body: 'A string inverter is a single inverter at the end of a series string of panels. A microinverter is a small inverter attached to each individual panel. A power optimizer is a panel-level electronic module that pairs with a central string inverter. All three convert the DC electricity from your panels into AC for your home.' },
      { heading: 'Cost', body: 'String inverters are typically the lowest cost option. Power optimizers add a small premium for the panel-level hardware. Microinverters are usually the most expensive option per panel. The cost difference per watt is often small in absolute dollars at residential scale — sometimes only a few hundred dollars on a typical system.' },
      { heading: 'Monitoring granularity', body: 'Microinverters and power optimizers report per-panel production data. String inverters report string-level data (one number per "string" of panels). Per-panel data is invaluable for catching underperformance early. If a panel fails or is heavily shaded, you\'ll see it on a per-panel graph but not on a string inverter graph.' },
      { heading: 'Shade tolerance', body: 'Microinverters and power optimizers convert DC to AC at the panel, so a shaded panel does not drag down the rest of the array. String inverters without optimizers can lose significant output when even one panel is partially shaded. For roofs with significant morning or afternoon shading, microinverters or optimizers are usually worth the small cost premium.' },
      { heading: 'Reliability and warranty', body: 'Modern string inverters and microinverters both have warranties of 10–25 years. Microinverters can be replaced individually if one fails; a string inverter is a single point of failure (though failures are uncommon). Power optimizers sit between the two — a faulty optimizer affects one panel, but the central inverter is still a single point of failure.' },
      { heading: 'Which one to choose', body: 'For most U.S. residential installs with good sun exposure and minimal shading, a string inverter is fine and saves you money. For shaded roofs, complex roofs with multiple orientations, or homeowners who want panel-level monitoring, microinverters or optimizers are worth the small premium. Your installer should explain which topology they recommend and why.' },
    ],
  },
  {
    slug: 'microinverter-shade-and-array-design',
    title: 'Microinverters, shade, and array design',
    h1: 'How shaded roofs complicate solar — and what to do about it',
    description: 'Practical guidance for solar installs on roofs that aren\'t perfectly sunny: how to model shade, what to expect, and where it changes the math.',
    metaDescription: 'Shading kills solar output. How to estimate shade on your roof, what to design around it, and when to skip solar for a different roof.',
    pillar: 'panels-and-equipment',
    datePublished: '2026-01-26',
    sections: [
      { heading: 'Why shade matters so much', body: 'A single shaded panel in a series string can reduce the output of the entire string to the level of the shaded panel — the "Christmas light" effect. Even partial shade from a chimney, a vent, or a nearby tree at certain hours can cause a string inverter to substantially curtail output. Microinverters and optimizers reduce this effect but don\'t eliminate it.' },
      { heading: 'Quantifying shade', body: 'Experienced installers use aerial imagery, on-site assessments, and tools like PVWatts with shading overlays. The result is a "shade factor" — a percentage reduction applied to the unshaded production estimate. A heavily shaded roof might lose 30%–50% of its theoretical output. Light morning or evening shading might cost only 5%–15%.' },
      { heading: 'When to consider a different roof or a different site', body: 'If your only viable roof is heavily shaded year-round, the solar economics are weak. Ground-mount systems on open ground may produce more — but they cost more to install. In some cases, a different array location (a back roof that is unshaded, a different array of panels) is the right answer.' },
      { heading: 'Tree management', body: 'Pruning a few trees that shade a roof can dramatically increase production and is sometimes cheaper than adding more panels. Discuss tree removal with your installer; in some jurisdictions, removal of significant trees requires a permit.' },
      { heading: 'Array design tradeoffs', body: 'You can design around shade by spreading panels across multiple strings so a shaded string doesn\'t limit the others, using microinverters or optimizers, or accepting some clipping with a slightly oversized array. Talk through these tradeoffs with your installer.' },
      { heading: 'When solar still makes sense on a shaded roof', body: 'If your electricity rate is high, the system economics can tolerate moderate shading. If the system is for backup power (paired with a battery) rather than maximum offset, you may accept some shading in exchange for siting the array where it best covers your loads. Talk to your installer about the realistic output expectations before signing.' },
    ],
  },
  {
    slug: 'cash-loan-lease-ppa',
    title: 'Cash, solar loan, lease, PPA — pros and cons',
    h1: 'Cash, solar loan, lease, PPA — pros and cons of each financing path',
    description: 'An honest, even-handed comparison of the four main ways U.S. homeowners pay for solar systems.',
    metaDescription: 'Cash vs solar loan vs lease vs PPA. Pros and cons of each financing path, including tax credit implications and resale considerations.',
    pillar: 'costs-and-financing',
    datePublished: '2026-01-18',
    sections: [
      { heading: 'The four paths', body: 'Cash means you pay in full and own the system outright. Loan means you finance the purchase and own the system. Lease means a third party owns the system on your roof and you pay a fixed monthly amount. PPA is similar to a lease but billed per kWh. Each has different cost, ownership, and tax implications.' },
      { heading: 'Cash: pros and cons', body: 'Cash gives you the cleanest economic picture: you own the equipment, qualify for any applicable tax credits, and avoid interest. The downside is the up-front capital requirement. Cash makes the most sense when you can afford the system without disrupting your other financial priorities and plan to stay in the home long enough to recover the investment.' },
      { heading: 'Loan: pros and cons', body: 'A loan lets you own the system while spreading the cost over 10–20 years. You keep the tax credits and the long-term upside. The cost is the interest rate and the obligation of a monthly payment regardless of how the system performs. A loan is usually the best non-cash option for homeowners with reasonable credit.' },
      { heading: 'Lease: pros and cons', body: 'A lease reduces or eliminates up-front cost. The lease owner gets the tax credit, owns the equipment, and is usually responsible for maintenance. You get a predictable monthly bill but lose the long-term upside of system ownership. Leases also complicate home sales — the new owner must qualify with the lease company or you pay a buyout.' },
      { heading: 'PPA: pros and cons', body: 'A PPA is the kWh-priced cousin of a lease. Same ownership and tax credit arrangement, but you pay per unit of electricity rather than a fixed monthly amount. PPAs often include an escalator — the per-kWh price rises over time, sometimes faster than your utility rate. Read the escalator carefully.' },
      { heading: 'How to decide', body: 'Cash if you have it and won\'t miss the opportunity cost. Loan if your credit and rate are reasonable and you plan to stay in the home long enough. Skip the lease/PPA unless your credit, income, or short-term ownership plans make ownership impractical. Your installer can talk you through the specifics, but it\'s your decision — push back if you need to.' },
    ],
  },
  {
    slug: 'reading-your-utility-bill-to-size-a-system',
    title: 'Reading your utility bill to size a system',
    h1: 'How to read your utility bill and size a system to it',
    description: 'The exact numbers your installer needs from your utility bill, and how to estimate your solar offset from 12 months of usage.',
    metaDescription: 'How to read your utility bill, what numbers your installer needs, and how to estimate the right solar system size from your annual usage.',
    pillar: 'going-solar',
    datePublished: '2026-01-08',
    sections: [
      { heading: 'What on your utility bill actually matters', body: 'Your annual kWh consumption is the single most important number. Your rate (per kWh) and your monthly fixed charges are second. The variety of rate plans (flat, tiered, time-of-use) matters for the value calculation but not for sizing.' },
      { heading: 'Why 12 months of history', body: 'Annual kWh lets you account for seasonal variation — your summer air-conditioning bills look very different from your spring shoulder season. A good solar quote uses at least 12 months of utility usage, ideally 24, to size the system. If you have less than 12 months of history, your installer can still proceed but the sizing carries more uncertainty.' },
      { heading: 'How to read time-of-use bills', body: 'A TOU bill separates usage into tiers or time periods (peak, off-peak, sometimes super-off-peak). Your bill typically shows each period separately. For solar savings modeling, you want the breakdown — exporting during the day (when rates are mid) and consuming in the evening (when rates are peak) is the most valuable pattern.' },
      { heading: 'When to look at fixed charges', body: 'Your monthly fixed charge (also called "basic charge" or "customer charge") does not go away with solar. Even a net-zero-energy home pays the fixed charges. So when estimating long-term bill savings, the fixed charges are subtracted from gross savings. A higher fixed charge means solar is a less attractive investment than a quote might suggest.' },
      { heading: 'Future load changes', body: 'If you are planning to add an EV, electrify heating, install a pool pump, add a home addition, or work from home, your load will grow. Forward-project your bill as part of the sizing conversation. The general answer for "should I size up now?" is usually yes if you know a major change is coming.' },
      { heading: 'A worked example', body: 'If your home uses 12,000 kWh per year in the U.S. Southwest, a well-sited 8 kW system might produce around 13,000 kWh/year — offsetting 100% of your usage. The same 8 kW in the U.S. Northwest might produce 9,000 kWh/year — offsetting 75%. Location, tilt, azimuth, and shading all change the math. Get specific numbers from your installer.' },
    ],
  },
  {
    slug: 'financing-options-cash-loan-ppa-lease',
    title: 'Financing options: cash, solar loan, PPA, lease',
    h1: 'Residential solar financing — what each option really costs',
    description: 'A practical guide to the four main financing paths for residential solar, with a checklist of what to verify in any loan or PPA contract.',
    metaDescription: 'Practical guidance on cash, solar loan, PPA, and lease financing for residential solar, including a contract checklist for each option.',
    pillar: 'costs-and-financing',
    datePublished: '2025-12-30',
    sections: [
      { heading: 'Why financing matters', body: 'The financing path changes the total cost of going solar and who benefits from incentives. Choosing wrongly can cost thousands over the life of the system. Choosing wisely can make solar cash-flow positive from month one.' },
      { heading: 'Cash', body: 'The simplest cost: your up-front payment, less any incentives you receive after filing taxes. No interest, no third party, no escalation. Cash is usually the cheapest total cost of ownership.' },
      { heading: 'Solar loan', body: 'A loan adds an interest rate and a term. The right loan pairs a competitive APR with the right term length and lets you prepay without penalty. Solar-focused lenders (GoodLeap, Mosaic, LightReach, Credit Human, and others) compete with home equity products. Watch for dealer fees that get embedded in the loan principal — they\'re not always disclosed clearly.' },
      { heading: 'Lease', body: 'A lease assigns ownership (and the federal tax credit, where applicable) to the lease holder. You pay a fixed monthly amount, often with an annual escalator. Read the escalator clause — a 3%–5% annual escalator can make the lease more expensive than the utility grid by year 10.' },
      { heading: 'PPA', body: 'A PPA bills per kWh, often with a per-kWh price set lower than your utility rate but rising on an annual escalator. The cost arithmetic is similar to a lease, just billed differently. Read the escalator and the per-kWh rate the same way.' },
      { heading: 'A contract checklist', body: 'For any solar contract (cash, loan, lease, or PPA): ask for total system cost, $/W figure, equipment list with make and model, warranty terms, projected first-year production, escalation rate (if lease/PPA), buyout terms (if lease/PPA), transferability to a new homeowner, and any dealer fees or adders. Read the contract fully before signing.' },
    ],
  },
  {
    slug: 'solar-active-vs-passive',
    title: 'Active vs passive solar — they are not the same thing',
    h1: 'Active vs passive solar — what each term really means',
    description: '"Active solar" usually means PV or solar thermal with mechanical help. "Passive solar" means designing a building to use the sun without mechanical systems.',
    metaDescription: 'Active solar vs passive solar — what each means for homeowners, what each costs, and where the confusion comes from.',
    pillar: 'panels-and-equipment',
    datePublished: '2025-12-20',
    sections: [
      { heading: 'Why the confusion', body: 'The word "solar" is used for very different things — photovoltaic (PV) panels, solar thermal hot water, passive solar building design, daylighting, and solar heating of air. They have very different cost, complexity, and benefits.' },
      { heading: 'Photovoltaic (active PV)', body: 'Photovoltaic panels convert sunlight directly into electricity. They\'re the most common "solar" you see on residential roofs. PV is a useful name: it describes what the technology does.' },
      { heading: 'Solar thermal', body: 'Solar thermal collectors heat a fluid (water or glycol) that\'s piped to a storage tank. Solar thermal is excellent for hot water and pool heating and is sometimes used for space heating. It is less common in U.S. residential applications today than PV.' },
      { heading: 'Passive solar building design', body: 'Passive solar is the design of a building to use the sun for heating, cooling, and lighting without mechanical equipment. South-facing windows, thermal mass, overhangs, and good insulation are the classic tools. Passive solar design predates PV by decades and is the foundation of good building design in many climates.' },
      { heading: 'What this site focuses on', body: 'For purposes of residential solar electricity generation, the focus is almost always on active PV. We\'ll occasionally reference passive design for context — well-oriented and well-insulated homes produce more usable solar energy per installed kW — but the systems discussed here are PV with optional batteries.' },
      { heading: 'How passive design helps your solar', body: 'A well-designed, energy-efficient home uses less electricity for heating and cooling, so a smaller solar system covers more of the bill. If you\'re planning new construction or a major remodel, talk to your designer about passive solar design before sizing the PV system.' },
    ],
  },
  {
    slug: 'off-grid-vs-grid-tied',
    title: 'Off-grid vs grid-tied solar',
    h1: 'Off-grid vs grid-tied solar — a homeowner decision tree',
    description: 'How to think about whether true off-grid solar makes sense for a U.S. residential property, and what grid-tied with battery can do instead.',
    metaDescription: 'Off-grid solar requires more battery capacity than most homeowners expect. Grid-tied with battery covers most resilience needs at lower cost.',
    pillar: 'battery-storage',
    datePublished: '2025-12-12',
    sections: [
      { heading: 'What "off-grid" actually requires', body: 'An off-grid home must generate all its electricity on-site and store enough to cover nights, cloudy days, and seasonal production dips. That usually means a much larger solar array and substantially more battery capacity than a grid-tied system. For most U.S. suburban homes, off-grid is multi-decade payback — usually not the right answer.' },
      { heading: 'What grid-tied with battery covers', body: 'A grid-tied solar system with a modest battery can power your critical loads during a typical outage (a few hours to a few days), participate in time-of-use bill management, and ride through short grid events without intervention. For most homeowners, this is the resilience story that makes sense.' },
      { heading: 'When off-grid is the right answer', body: 'Off-grid makes sense when the cost of grid extension is prohibitive (remote rural land, new construction far from utility lines) or when the property cannot legally connect to the grid. Off-grid also has a place for cabins, RVs, and certain rural applications. Talk to a designer with off-grid experience if you\'re considering this path.' },
      { heading: 'Sizing an off-grid system', body: 'Off-grid systems are sized to your worst-case load during your longest likely low-production stretch — typically 3–7 days of autonomy in a U.S. climate. That usually means a much larger battery bank than a grid-tied setup. Generator backup is often part of an off-grid system to cover multi-day cloudy periods.' },
      { heading: 'Battery technology for off-grid', body: 'Lithium iron phosphate (LFP) has become the most common chemistry for residential off-grid applications due to cycle life, depth of discharge, and operating temperature tolerance. Lead-acid remains cheaper up-front but requires more frequent replacement. Talk to your designer about total cost of ownership, not just up-front price.' },
      { heading: 'A practical workflow', body: 'If your goal is resilience: start with grid-tied solar, add a battery sized to your critical loads and target outage duration. If your goal is energy independence and you can pay for it: design an off-grid system with a designer experienced in your climate. Most homeowners fall comfortably into the first category.' },
    ],
  },
  {
    slug: 'solar-panel-degradation',
    title: 'Solar panel degradation — what it really means',
    h1: 'Solar panel degradation — what "0.5% per year" actually means',
    description: 'How solar panels lose performance over time, the difference between degradation and failure, and what to look for in a performance warranty.',
    metaDescription: 'How solar panels degrade over time, the standard 0.5% per year figure, and how to read a 25-year performance warranty.',
    pillar: 'panels-and-equipment',
    datePublished: '2025-12-02',
    sections: [
      { heading: 'What degradation is', body: 'A new solar panel produces close to its rated output. Over the years, every solar panel produces slightly less — this is degradation. Modern monocrystalline silicon panels degrade at roughly 0.3%–0.5% per year, depending on the cell technology and operating conditions.' },
      { heading: 'Year one vs subsequent years', body: 'Manufacturers typically allow a small first-year degradation (often 2%–3%) — meaning the panel may produce 97%–98% of nameplate in year one even under ideal conditions. After year one, the annual rate drops to roughly 0.3%–0.5% per year. A typical 25-year performance warranty guarantees the panel will produce about 85%–88% of nameplate in year 25.' },
      { heading: 'Degradation vs failure', body: 'Degradation is gradual and expected. Failure is a sudden drop or complete loss of output. Modern panels rarely fail outright, but they can be damaged (physical breakage, hot spots, junction box failures). A performance warranty covers gradual degradation below the warranted curve; a product warranty covers defects and failures.' },
      { heading: 'Hot spots and PID', body: 'Hot spots are localized cells that heat up disproportionately, often due to shading, cell defects, or soiling. Potential-induced degradation (PID) is a voltage-driven loss that affects some panels in high-voltage systems. Both are uncommon in well-designed residential installs but worth understanding.' },
      { heading: 'What you can do', body: 'Keep panels clean. Monitor output and investigate unexpected drops. Make sure your installer uses panels with a strong 25-year performance warranty and registers the warranty in your name. Avoid shaded installations that drive uneven degradation.' },
      { heading: 'What to look for in a warranty', body: 'A standard performance warranty should commit the panel to produce a defined percentage of nameplate at year 25 (typically 84%–90% depending on the tier). A product warranty should cover defects for at least 12 years (industry standard is 25 years on premium panels). Read both for transferability to a future homeowner.' },
    ],
  },
  {
    slug: 'solar-roof-age-and-reroofing',
    title: 'Solar, roof age, and reroofing — how to sequence them',
    h1: 'Solar and your roof — sequencing reroofing and the solar install',
    description: 'If your roof is nearing end of life, the order of operations matters. Reroof first, then install solar — usually.',
    metaDescription: 'Should you reroof before installing solar? In most cases yes. Here is how to think about timing, cost, and the optimal sequence.',
    pillar: 'going-solar',
    datePublished: '2025-11-22',
    sections: [
      { heading: 'Why reroofing usually comes first', body: 'Solar panels are designed to stay on a roof for 25+ years. If your roof needs to be replaced within that window, the cost and disruption of removing and reinstalling the panels is significant. Most installers will require you to reroof first if the roof has fewer than 10 years of useful life remaining.' },
      { heading: 'How to evaluate roof condition', body: 'A roofing contractor or your solar installer can tell you roughly how many useful years your roof has left. Asphalt shingle roofs typically last 20–25 years in U.S. climates. Tile, metal, and slate can last much longer. The closer to end of life your roof is, the stronger the case for replacing it first.' },
      { heading: 'The math', body: 'A typical U.S. reroof costs several thousand to mid-five-figures depending on roof size, material, and complexity. Removing and reinstalling a solar array costs more than the reroof itself — usually a few thousand dollars — so replacing the roof preemptively is usually cheaper than waiting.' },
      { heading: 'When reroofing and solar can happen together', body: 'Some installers coordinate with roofing contractors to do both at once. The roofer strips the old roof, installs the new underlayment and shingles, and the solar crew mounts the new array on the same trip. This can save on-site time and coordination headaches. Ask your installer if they have a roofing partner or if they recommend a separate reroof first.' },
      { heading: 'What to tell your roofer', body: 'If you plan to put solar on the new roof within a few years, tell the roofer so they can plan attachment-friendly layouts. Many roofers will be aware of standard solar attachment patterns; some will coordinate with your installer to mark the rafters and ensure the new roof carries the load.' },
      { heading: 'A practical sequence', body: 'If your roof is in the first 60% of its useful life: install solar now. If your roof is in the last 40%: reroof first, then install solar within a few months. If you\'re already reroofing because of damage or age, plan for solar as the next step.' },
    ],
  },
  {
    slug: 'how-inverter-choice-affects-output',
    title: 'How inverter choice affects solar output',
    h1: 'How your inverter choice affects system output',
    description: 'The three inverter topologies have different efficiency curves, monitoring granularity, and shade tolerance. What that means for your actual annual production.',
    metaDescription: 'How string vs microinverter vs power optimizer affects the electricity your system actually produces each year.',
    pillar: 'panels-and-equipment',
    datePublished: '2025-11-12',
    sections: [
      { heading: 'Inverter efficiency', body: 'Every inverter loses a small percentage of the DC electricity it processes. String inverters are typically 96%–98% efficient. Microinverters and power optimizers are typically 95%–97% efficient at the panel level. The exact figure depends on the model and on how heavily loaded the inverter is at any moment.' },
      { heading: 'CEC efficiency vs peak efficiency', body: 'Manufacturers list peak efficiency in their datasheet, but the more useful number is the CEC-weighted efficiency, which averages performance across a realistic loading profile. CEC efficiency is almost always lower than peak efficiency. Look for the CEC figure when comparing inverters.' },
      { heading: 'Shade and topology', body: 'A microinverter or power optimizer system holds up better under partial shading than a string inverter system. If your roof has morning or afternoon shade, the production difference can be 5%–15% per year. For completely unshaded roofs, the difference is small.' },
      { heading: 'Clipping', body: 'Inverters have a maximum AC output. If your panels produce more DC than the inverter can convert (a situation called clipping), the extra production is lost. Common examples: a 7 kW DC array on a 6 kW AC inverter clips during peak sun. The loss is usually a small percentage over the year but is sometimes worth designing around.' },
      { heading: 'Monitoring and observability', body: 'Panel-level monitoring (from microinverters or optimizers) catches problems like a single faulty panel or a shaded section early. String-inverter monitoring shows the sum across each string. For most homeowners this is a difference in detection speed rather than a functional difference in production.' },
      { heading: 'Choosing for your roof', body: 'A small, unshaded roof: string inverter is fine. A complex roof with multiple orientations: microinverter or optimizer often pays back. A heavily shaded roof: panel-level electronics are usually worth the cost premium. Your installer should walk you through which topology is right for your specific roof.' },
    ],
  },
  {
    slug: 'ground-mount-vs-rooftop',
    title: 'Ground-mount vs rooftop solar — when each makes sense',
    h1: 'Ground-mount vs rooftop solar — when each makes sense',
    description: 'Ground-mount solar opens up a different geometry than rooftop. The economics are different, the permits are different, and the use cases are narrower.',
    metaDescription: 'When to put solar on the ground instead of the roof. Cost differences, permit differences, and the kinds of properties where each makes sense.',
    pillar: 'going-solar',
    datePublished: '2025-11-02',
    sections: [
      { heading: 'When ground-mount is the obvious answer', body: 'If your roof is shaded, structurally unsuitable, or covered with obstructions, ground-mount becomes the practical alternative. Properties with usable open land and good sun exposure benefit most. Some rural and agricultural properties prefer ground-mount because it\'s easy to access for maintenance.' },
      { heading: 'Cost differences', body: 'Ground-mount systems typically cost more per watt than rooftop systems. The racking is more substantial (heavy posts, often concrete footings), and the trenching from the array to your home\'s electrical service adds labor. Expect ground-mount systems to run roughly 10%–25% more than equivalent rooftop systems per watt.' },
      { heading: 'Permits and inspections', body: 'Ground-mount systems usually require a building permit (often the same permit office as your house), sometimes an electrical permit, and often an additional zoning review. Your installer should handle this. Some jurisdictions have rules about how close ground-mount arrays can be to property lines.' },
      { heading: 'Production differences', body: 'A ground-mount array is typically installed at the optimum tilt and orientation, often tilted at your latitude. That usually produces more kWh per kW than a rooftop array constrained by roof pitch and orientation. The production premium is sometimes 5%–15% per kW depending on the roof constraints.' },
      { heading: 'Land considerations', body: 'Ground-mount systems consume yard space. A typical residential ground-mount array needs several hundred square feet of usable land with good sun exposure year-round. Plan for the land use, the screening, and the visibility from neighbors.' },
      { heading: 'Choosing the right approach', body: 'Most suburban U.S. homes put solar on the roof. If your roof is constrained (orientation, shade, structural limits) and you have usable land, ground-mount is worth a discussion. If you have both options, ask your installer to model both and compare total cost, total production, and payback.' },
    ],
  },
];

export function guideBySlug(slug: string): Guide | undefined {
  return guides.find((g) => g.slug === slug);
}
