// US states data — 50 entries. Each entry is the basis for /states/[slug]/page.tsx.
// DSIRE links point to the canonical state detail page on DSIRE when applicable.
// "policyPosture" is a neutral, factual summary category — not a fabricated dollar amount.

export interface StatePageContent {
  slug: string;     // url segment
  name: string;     // "California"
  abbr: string;     // "CA"
  capital: string;  // "Sacramento"
  region: 'Northeast' | 'Midwest' | 'South' | 'West' | 'Southwest';
  climate: string;          // factual climate note
  electricityContext: string; // factual grid/utility note
  policyPosture: string;    // one-sentence factual posture
  dsireUrl: string;         // DSIRE state summary or search
  commonQuestions: string[]; // visible FAQ prompts on the state page
}

export const states: StatePageContent[] = [
  { slug: 'alabama', name: 'Alabama', abbr: 'AL', capital: 'Montgomery', region: 'South', climate: 'Humid subtropical; long, hot summers and mild winters.', electricityContext: 'Alabama Power (a regulated investor-owned utility) serves most of the state; TVA serves parts of north Alabama.', policyPosture: 'No statewide solar mandate; limited statewide incentives. Local utility tariffs vary.', dsireUrl: 'https://programs.dsireusa.org/system/program/al', commonQuestions: ['Is solar worth it in Alabama?', 'What rebates exist for Alabama homeowners?', 'How does Alabama Power interconnect a solar system?'] },
  { slug: 'alaska', name: 'Alaska', abbr: 'AK', capital: 'Juneau', region: 'West', climate: 'Subarctic to arctic; extreme variation in daylight across seasons and regions.', electricityContext: 'Many remote communities operate on isolated microgrids rather than the interconnected railbelt grid.', policyPosture: 'No statewide rooftop solar rebate program; some community and tribal renewable programs operate locally.', dsireUrl: 'https://programs.dsireusa.org/system/program/ak', commonQuestions: ['Can rooftop solar work in Alaska winters?', 'What are remote-grid solar options?', 'Are there Alaska-specific solar incentives?'] },
  { slug: 'arizona', name: 'Arizona', abbr: 'AZ', capital: 'Phoenix', region: 'Southwest', climate: 'Hot desert; abundant sunshine, very high summer temperatures that affect panel efficiency.', electricityContext: 'Salt River Project, Arizona Public Service, Tucson Electric Power, and UniSource serve most customers.', policyPosture: 'Solar has a strong residential presence; net metering successor tariffs vary by utility.', dsireUrl: 'https://programs.dsireusa.org/system/program/az', commonQuestions: ['How does Arizona net metering work today?', 'What should I ask an installer in Arizona?', 'Are Arizona solar incentives still available?'] },
  { slug: 'arkansas', name: 'Arkansas', abbr: 'AR', capital: 'Little Rock', region: 'South', climate: 'Humid subtropical; hot summers, mild winters.', electricityContext: 'Entergy Arkansas and Oklahoma Gas and Electric (serving western AR) are major utilities.', policyPosture: 'Net metering available at the state level; tax incentives have changed over time.', dsireUrl: 'https://programs.dsireusa.org/system/program/ar', commonQuestions: ['Does Arkansas offer net metering?', 'What is the Arkansas solar property tax exemption?', 'How do I compare Arkansas installers?'] },
  { slug: 'california', name: 'California', abbr: 'CA', capital: 'Sacramento', region: 'West', climate: 'Mediterranean to desert and alpine; very high solar resource across most regions.', electricityContext: 'Three large investor-owned utilities (PG&E, SCE, SDG&E) plus many municipal utilities (SMUD, LADWP, etc.).', policyPosture: 'Long history of solar policy including NEM 1.0, 2.0, and 3.0 tariff revisions; state mandates for new construction solar.', dsireUrl: 'https://programs.dsireusa.org/system/program/ca', commonQuestions: ['What is NEM 3.0 and how does it affect me?', 'How do CPUC decisions affect residential solar?', 'Are California batteries worth it under NEM 3.0?'] },
  { slug: 'colorado', name: 'Colorado', abbr: 'CO', capital: 'Denver', region: 'West', climate: 'High-altitude semi-arid; strong sunshine, cold winters at elevation.', electricityContext: 'Xcel Energy serves most customers; black Hills Energy, CORE Electric Cooperative serve other areas.', policyPosture: 'Xcel Energy offers net metering; state sales-tax exemption on residential solar was in place historically.', dsireUrl: 'https://programs.dsireusa.org/system/program/co', commonQuestions: ['Does Colorado still have a solar sales tax exemption?', 'How does Xcel Energy net metering work?', 'What is the Colorado solar rebate program?'] },
  { slug: 'connecticut', name: 'Connecticut', abbr: 'CT', capital: 'Hartford', region: 'Northeast', climate: 'Humid continental; cold winters, warm summers.', electricityContext: 'Eversource and United Illuminating are the two main electric utilities.', policyPosture: 'Residential Solar Renewable Energy Credit (RSREC) program structure; state ZREC program for commercial.', dsireUrl: 'https://programs.dsireusa.org/system/program/ct', commonQuestions: ['What is Connecticut\'s RSREC program?', 'Are Eversource virtual net metering credits available?', 'How does Connecticut\'s incentive stack work?'] },
  { slug: 'delaware', name: 'Delaware', abbr: 'DE', capital: 'Dover', region: 'South', climate: 'Humid subtropical; moderate winters, warm summers.', electricityContext: 'Delmarva Power serves most of the state.', policyPosture: 'Solar Renewable Energy Credit (SREC) program; modest residential rebate history.', dsireUrl: 'https://programs.dsireusa.org/system/program/de', commonQuestions: ['Does Delaware have an SREC program today?', 'What are Delaware\'s solar property tax rules?', 'How do I find a Delaware solar installer?'] },
  { slug: 'florida', name: 'Florida', abbr: 'FL', capital: 'Tallahassee', region: 'South', climate: 'Humid subtropical to tropical; intense sun, hurricane risk.', electricityContext: 'Florida Power & Light (FPL), Duke Energy Florida, Tampa Electric, and many municipal / co-op utilities.', policyPosture: 'Net metering was rolled back; solar rights / solar easements protect against HOA restrictions under Florida law.', dsireUrl: 'https://programs.dsireusa.org/system/program/fl', commonQuestions: ['What happened to Florida net metering?', 'Do Florida HOA rules block solar?', 'Should I add batteries in hurricane-prone Florida?'] },
  { slug: 'georgia', name: 'Georgia', abbr: 'GA', capital: 'Atlanta', region: 'South', climate: 'Humid subtropical; long hot summers, mild winters.', electricityContext: 'Georgia Power (a regulated IOU) is the largest utility; EMC cooperatives cover rural areas.', policyPosture: 'Georgia Power files periodic solar tariff changes; statewide sales-tax exemption has been in place.', dsireUrl: 'https://programs.dsireusa.org/system/program/ga', commonQuestions: ['What is the Georgia Power solar tariff today?', 'Do Georgia EMCs offer net metering?', 'Are there Georgia state solar rebates?'] },
  { slug: 'hawaii', name: 'Hawaii', abbr: 'HI', capital: 'Honolulu', region: 'West', climate: 'Tropical; very consistent solar resource but salt-air and humidity considerations.', electricityContext: 'Hawaiian Electric Company (HECO) serves most of the state; independent grids per island.', policyPosture: 'Net metering ended for new customers; battery storage is incentivized; very high electricity prices drive strong economics.', dsireUrl: 'https://programs.dsireusa.org/system/program/hi', commonQuestions: ['What replaced Hawaii net metering?', 'Why is Hawaii battery storage essential?', 'How do I get interconnected with HECO today?'] },
  { slug: 'idaho', name: 'Idaho', abbr: 'ID', capital: 'Boise', region: 'West', climate: 'Mostly high-desert and mountain; hot summers, cold winters.', electricityContext: 'Idaho Power and Rocky Mountain Power serve most of the state.', policyPosture: 'Modest state-level solar policy; utility tariff-driven approach.', dsireUrl: 'https://programs.dsireusa.org/system/program/id', commonQuestions: ['What is Idaho Power\'s net metering today?', 'Does Idaho offer a solar property tax exemption?', 'Are there Idaho solar incentives?'] },
  { slug: 'illinois', name: 'Illinois', abbr: 'IL', capital: 'Springfield', region: 'Midwest', climate: 'Humid continental; cold winters, hot summers.', electricityContext: 'ComEd and Ameren serve most customers; many smaller municipal utilities elsewhere.', policyPosture: 'Illinois Solar for All and Adjustable Block Program (now called the Illinois Shines Program); SMART Illinois-type incentives.', dsireUrl: 'https://programs.dsireusa.org/system/program/il', commonQuestions: ['What is Illinois Shines / Adjustable Block Program?', 'How does ComEd net metering work?', 'Are Illinois solar incentives stable?'] },
  { slug: 'indiana', name: 'Indiana', abbr: 'IN', capital: 'Indianapolis', region: 'Midwest', climate: 'Humid continental; varied temperatures, four-season.', electricityContext: 'Duke Energy Indiana, Indiana Michigan Power, AES Indiana, and NIPSCO.', policyPosture: 'Net metering in place; no state tax credit currently active.', dsireUrl: 'https://programs.dsireusa.org/system/program/in', commonQuestions: ['Does Indiana offer net metering?', 'What is Indiana\'s solar tax treatment?', 'How do I qualify for Indiana solar incentives?'] },
  { slug: 'iowa', name: 'Iowa', abbr: 'IA', capital: 'Des Moines', region: 'Midwest', climate: 'Humid continental; strong seasonal variation.', electricityContext: 'MidAmerican Energy and Alliant Energy serve most customers.', policyPosture: 'Net metering in place; small state-administered incentives have varied over time.', dsireUrl: 'https://programs.dsireusa.org/system/program/ia', commonQuestions: ['How does Iowa net metering work?', 'What is Iowa\'s sales-tax policy for solar?', 'Are there Iowa solar rebates?'] },
  { slug: 'kansas', name: 'Kansas', abbr: 'KS', capital: 'Topeka', region: 'Midwest', climate: 'Humid continental to semi-arid; high winds, hot summers.', electricityContext: 'Evergy and Sunflower Electric Power are major providers.', policyPosture: 'Net metering in place; modest state incentives historically.', dsireUrl: 'https://programs.dsireusa.org/system/program/ks', commonQuestions: ['What is the Kansas solar property tax exemption?', 'Does Kansas net meter?', 'How do I compare Kansas solar installers?'] },
  { slug: 'kentucky', name: 'Kentucky', abbr: 'KY', capital: 'Frankfort', region: 'South', climate: 'Humid subtropical; hot summers, mild winters.', electricityContext: 'Kentucky Utilities and Louisville Gas & Electric are major utilities.', policyPosture: 'Net metering in place; state-level incentives have varied.', dsireUrl: 'https://programs.dsireusa.org/system/program/ky', commonQuestions: ['Does Kentucky have net metering?', 'What is Kentucky\'s solar tax treatment?', 'Are there Kentucky solar incentives?'] },
  { slug: 'louisiana', name: 'Louisiana', abbr: 'LA', capital: 'Baton Rouge', region: 'South', climate: 'Humid subtropical; hot, muggy, hurricane-prone.', electricityContext: 'Entergy Louisiana and Cleco are major utilities.', policyPosture: 'Net metering in place; state incentives modest historically.', dsireUrl: 'https://programs.dsireusa.org/system/program/la', commonQuestions: ['Does Louisiana have net metering?', 'How are solar systems priced in Louisiana?', 'What about hurricane resilience with solar?'] },
  { slug: 'maine', name: 'Maine', abbr: 'ME', capital: 'Augusta', region: 'Northeast', climate: 'Humid continental; long cold winters, short cool summers.', electricityContext: 'Versant Power (formerly Emera Maine) and Central Maine Power.', policyPosture: 'Net metering in place; step-change incentives through CMP / Versant tariff structures.', dsireUrl: 'https://programs.dsireusa.org/system/program/me', commonQuestions: ['How does Maine net metering work?', 'What is the Maine solar rebate program?', 'How do I find a Maine installer?'] },
  { slug: 'maryland', name: 'Maryland', abbr: 'MD', capital: 'Annapolis', region: 'South', climate: 'Humid subtropical; four seasons, hot summers.', electricityContext: 'BGE, Pepco, Potomac Edison (FirstEnergy), and SMECO (cooperative).', policyPosture: 'Maryland Solar Renewable Energy Credit (SREC) program; state-administered blocks; community solar programs.', dsireUrl: 'https://programs.dsireusa.org/system/program/md', commonQuestions: ['What is the Maryland SREC program?', 'How does BGE net metering work?', 'How do Maryland community solar programs work?'] },
  { slug: 'massachusetts', name: 'Massachusetts', abbr: 'MA', capital: 'Boston', region: 'Northeast', climate: 'Humid continental; cold winters, warm summers.', electricityContext: 'Eversource, National Grid, and Unitil are the main electric utilities.', policyPosture: 'Massachusetts Solar Massachusetts Renewable Target (SMART) program; production incentives; net metering caps vary by utility.', dsireUrl: 'https://programs.dsireusa.org/system/program/ma', commonQuestions: ['How does Massachusetts SMART work?', 'What is the difference between SMART and net metering credits?', 'Are Massachusetts solar incentives funded?'] },
  { slug: 'michigan', name: 'Michigan', abbr: 'MI', capital: 'Lansing', region: 'Midwest', climate: 'Humid continental; cold, snowy winters, warm summers.', electricityContext: 'Consumers Energy, DTE Energy, and many rural electric cooperatives.', policyPosture: 'Net metering at the state level; the MI Solar Communities program supports low-income access.', dsireUrl: 'https://programs.dsireusa.org/system/program/mi', commonQuestions: ['Does Michigan have net metering?', 'How does DTE interconnect solar?', 'What incentives exist for Michigan solar?'] },
  { slug: 'minnesota', name: 'Minnesota', abbr: 'MN', capital: 'Saint Paul', region: 'Midwest', climate: 'Humid continental; very cold winters, warm summers.', electricityContext: 'Xcel Energy, Minnesota Power, Otter Tail Power, and many cooperatives.', policyPosture: 'Made in Minnesota solar incentives have ended for new applications but legacy projects continue; net metering persists.', dsireUrl: 'https://programs.dsireusa.org/system/program/mn', commonQuestions: ['What ended with Minnesota\'s Made in Minnesota program?', 'How does Xcel Minnesota net metering work?', 'Are Minnesota solar rebates available?'] },
  { slug: 'mississippi', name: 'Mississippi', abbr: 'MS', capital: 'Jackson', region: 'South', climate: 'Humid subtropical; hot, humid summers and mild winters.', electricityContext: 'Entergy Mississippi and Mississippi Power are major utilities.', policyPosture: 'Net metering in place; modest state incentives historically.', dsireUrl: 'https://programs.dsireusa.org/system/program/ms', commonQuestions: ['Does Mississippi offer net metering?', 'What is the Mississippi solar tax treatment?', 'Are there Mississippi solar incentives?'] },
  { slug: 'missouri', name: 'Missouri', abbr: 'MO', capital: 'Jefferson City', region: 'Midwest', climate: 'Humid continental; hot summers, cold winters, severe storms.', electricityContext: 'Ameren Missouri and Evergy Missouri are the major utilities.', policyPosture: 'Net metering in place; state property tax exemption for solar has existed.', dsireUrl: 'https://programs.dsireusa.org/system/program/mo', commonQuestions: ['Does Missouri offer a solar property tax exemption?', 'How does Ameren Missouri net metering work?', 'What Missouri solar rebates exist?'] },
  { slug: 'montana', name: 'Montana', abbr: 'MT', capital: 'Helena', region: 'West', climate: 'High-plains and mountain; cold winters, mild summers.', electricityContext: 'NorthWestern Energy serves most customers.', policyPosture: 'Net metering at the state level; some utility tariff changes over time.', dsireUrl: 'https://programs.dsireusa.org/system/program/mt', commonQuestions: ['What is Montana\'s net metering tariff?', 'Does Montana have a solar property tax exemption?', 'Are Montana solar incentives available?'] },
  { slug: 'nebraska', name: 'Nebraska', abbr: 'NE', capital: 'Lincoln', region: 'Midwest', climate: 'Humid continental to semi-arid; wide temperature swings, strong winds.', electricityContext: 'Public power is dominant; OPPD, NPPD, and LES are major providers, plus many districts.', policyPosture: 'Net metering statewide with relatively uniform rules across public-power utilities.', dsireUrl: 'https://programs.dsireusa.org/system/program/ne', commonQuestions: ['How does Nebraska\'s public power model affect solar?', 'Is net metering available in Nebraska?', 'What Nebraska solar incentives exist?'] },
  { slug: 'nevada', name: 'Nevada', abbr: 'NV', capital: 'Carson City', region: 'West', climate: 'Mostly arid and semi-arid; high desert, abundant sunshine.', electricityContext: 'NV Energy (Sierra Pacific Power and Nevada Power) is the dominant utility.', policyPosture: 'Net metering was restored after 2017 changes; NV Energy solar tariffs continue to evolve.', dsireUrl: 'https://programs.dsireusa.org/system/program/nv', commonQuestions: ['How does Nevada net metering work today?', 'What is the NV Energy solar tariff?', 'What incentives exist for solar in Nevada?'] },
  { slug: 'new-hampshire', name: 'New Hampshire', abbr: 'NH', capital: 'Concord', region: 'Northeast', climate: 'Humid continental; long cold winters, warm summers.', electricityContext: 'Eversource and Unitil serve most of the state.', policyPosture: 'Net metering in place; modest residential rebate history.', dsireUrl: 'https://programs.dsireusa.org/system/program/nh', commonQuestions: ['What is New Hampshire\'s net metering tariff?', 'Are NH solar incentives still funded?', 'How do I get a NH solar quote?'] },
  { slug: 'new-jersey', name: 'New Jersey', abbr: 'NJ', capital: 'Trenton', region: 'Northeast', climate: 'Humid subtropical; warm summers, cold winters.', electricityContext: 'Public Service Electric & Gas (PSE&G), JCP&L, Atlantic City Electric, and Rockland Electric.', policyPosture: 'Successor Solar Incentive (SuSI) program replaced SREC; net metering capped per utility.', dsireUrl: 'https://programs.dsireusa.org/system/program/nj', commonQuestions: ['What replaced New Jersey SRECs?', 'How does SuSI work in NJ?', 'What is the difference between SuSI and net metering?'] },
  { slug: 'new-mexico', name: 'New Mexico', abbr: 'NM', capital: 'Santa Fe', region: 'Southwest', climate: 'Mostly arid and semi-arid; strong sunshine, cool nights.', electricityContext: 'PNM and El Paso Electric serve most customers.', policyPosture: 'Net metering in place; state-administered programs have changed over time.', dsireUrl: 'https://programs.dsireusa.org/system/program/nm', commonQuestions: ['What is New Mexico\'s net metering policy today?', 'Does New Mexico have a community solar program?', 'How do I find an installer in NM?'] },
  { slug: 'new-york', name: 'New York', abbr: 'NY', capital: 'Albany', region: 'Northeast', climate: 'Humid continental; four distinct seasons.', electricityContext: 'Con Edison, National Grid, NYSEG, RG&E, Central Hudson, O&R, and LIPA on Long Island.', policyPosture: 'NY-Sun incentive program incentivizes residential and small commercial solar; Community DG program serves shared sites.', dsireUrl: 'https://programs.dsireusa.org/system/program/ny', commonQuestions: ['How does NY-Sun work?', 'What is a Community Distributed Generation project?', 'Are NY solar incentives funded in 2026?'] },
  { slug: 'north-carolina', name: 'North Carolina', abbr: 'NC', capital: 'Raleigh', region: 'South', climate: 'Humid subtropical; moderate, four-season.', electricityContext: 'Duke Energy Carolinas and Duke Energy Progress are the dominant utilities.', policyPosture: 'Net metering in place; state-level solar policy has been active; Duke tariffs continue to evolve.', dsireUrl: 'https://programs.dsireusa.org/system/program/nc', commonQuestions: ['What is NC\'s net metering policy today?', 'How does Duke Energy interconnect solar?', 'What NC solar incentives exist?'] },
  { slug: 'north-dakota', name: 'North Dakota', abbr: 'ND', capital: 'Bismarck', region: 'Midwest', climate: 'Continental; cold winters, warm summers.', electricityContext: 'Basin Electric Power Cooperative and investor-owned Montana-Dakota Utilities serve much of the state.', policyPosture: 'Modest state-level solar incentives; net metering available.', dsireUrl: 'https://programs.dsireusa.org/system/program/nd', commonQuestions: ['What is North Dakota\'s net metering policy?', 'Does ND have a solar property tax exemption?', 'Are ND solar incentives available?'] },
  { slug: 'ohio', name: 'Ohio', abbr: 'OH', capital: 'Columbus', region: 'Midwest', climate: 'Humid continental; cold winters, hot summers.', electricityContext: 'AEP Ohio, Duke Energy Ohio, AES Ohio, FirstEnergy (Ohio Edison / Illuminating), and Dayton Power & Light.', policyPosture: 'Net metering in place; the state property tax exemption for solar has existed for residential systems.', dsireUrl: 'https://programs.dsireusa.org/system/program/oh', commonQuestions: ['Does Ohio offer a solar property tax exemption?', 'How does AEP Ohio net metering work?', 'What Ohio solar incentives exist?'] },
  { slug: 'oklahoma', name: 'Oklahoma', abbr: 'OK', capital: 'Oklahoma City', region: 'South', climate: 'Humid subtropical to semi-arid; strong winds, hot summers.', electricityContext: 'OG&E and PSO are major utilities.', policyPosture: 'Net metering in place; state-administered programs modest.', dsireUrl: 'https://programs.dsireusa.org/system/program/ok', commonQuestions: ['How does OG&E net metering work?', 'Does Oklahoma have a solar property tax exemption?', 'What OK solar incentives exist?'] },
  { slug: 'oregon', name: 'Oregon', abbr: 'OR', capital: 'Salem', region: 'West', climate: 'Mild, wet in the west; high desert in the east.', electricityContext: 'Portland General Electric and Pacific Power are major IOUs; many consumer-owned utilities elsewhere.', policyPosture: 'Net metering tariff in place; state solar + storage incentives have existed.', dsireUrl: 'https://programs.dsireusa.org/system/program/or', commonQuestions: ['How does Oregon net metering work?', 'What is the Oregon solar rebate?', 'Does Oregon have a solar property tax exemption?'] },
  { slug: 'pennsylvania', name: 'Pennsylvania', abbr: 'PA', capital: 'Harrisburg', region: 'Northeast', climate: 'Humid continental; four seasons.', electricityContext: 'PPL, FirstEnergy (Met-Ed, Penelec, West Penn Power), PECO, Duquesne Light, and many rural co-ops.', policyPosture: 'Net metering in place; state SREC program ended for new applications.', dsireUrl: 'https://programs.dsireusa.org/system/program/pa', commonQuestions: ['What is the Pennsylvania SREC program status?', 'How does PPL net metering work in PA?', 'Does PA have a solar property tax exemption?'] },
  { slug: 'rhode-island', name: 'Rhode Island', abbr: 'RI', capital: 'Providence', region: 'Northeast', climate: 'Humid continental; cold winters, warm summers.', electricityContext: 'Rhode Island Energy (formerly National Grid RI).', policyPosture: 'Net metering available; state Renewable Energy Fund finances modest programs.', dsireUrl: 'https://programs.dsireusa.org/system/program/ri', commonQuestions: ['How does RI net metering work?', 'What is the Rhode Island solar rebate?', 'Are RI solar incentives still funded?'] },
  { slug: 'south-carolina', name: 'South Carolina', abbr: 'SC', capital: 'Columbia', region: 'South', climate: 'Humid subtropical; hot summers, mild winters.', electricityContext: 'Dominion Energy South Carolina and Duke Energy Carolinas.', policyPosture: 'Net metering in place; state property tax exemption for solar (25% cap) has existed.', dsireUrl: 'https://programs.dsireusa.org/system/program/sc', commonQuestions: ['Does South Carolina offer a solar property tax exemption?', 'How does Dominion net metering work in SC?', 'What SC solar incentives exist?'] },
  { slug: 'south-dakota', name: 'South Dakota', abbr: 'SD', capital: 'Pierre', region: 'Midwest', climate: 'Continental; cold winters, hot summers.', electricityContext: 'Investor-owned utilities plus electric cooperatives; many smaller municipal utilities.', policyPosture: 'Net metering in place; modest state-administered incentives.', dsireUrl: 'https://programs.dsireusa.org/system/program/sd', commonQuestions: ['What is SD\'s net metering policy?', 'Does SD have a solar property tax exemption?', 'Are South Dakota solar incentives available?'] },
  { slug: 'tennessee', name: 'Tennessee', abbr: 'TN', capital: 'Nashville', region: 'South', climate: 'Humid subtropical; hot summers, mild winters.', electricityContext: 'TVA serves most of the state; Nashville Electric Service and Memphis Light, Gas and Water in their cities.', policyPosture: 'TVA\'s Generation Partners / "Dispersed Power Producer" tariff shapes much of TN\'s residential solar rules.', dsireUrl: 'https://programs.dsireusa.org/system/program/tn', commonQuestions: ['How does TVA handle rooftop solar?', 'What is the Tennessee solar property tax treatment?', 'Are TN solar incentives available?'] },
  { slug: 'texas', name: 'Texas', abbr: 'TX', capital: 'Austin', region: 'South', climate: 'Vast — humid subtropical east, semi-arid west, hot summers statewide.', electricityContext: 'Oncor, CenterPoint, AEP Texas, TNMP, and the deregulated ERCOT market with many retail electricity providers.', policyPosture: 'No state-level net metering mandate; market-driven; "value of solar" tariffs vary by utility and REP.', dsireUrl: 'https://programs.dsireusa.org/system/program/tx', commonQuestions: ['How does Texas net metering / export credits work?', 'Why are Texas electricity rates so volatile for solar?', 'How do I choose a TX installer?'] },
  { slug: 'utah', name: 'Utah', abbr: 'UT', capital: 'Salt Lake City', region: 'West', climate: 'Arid to semi-arid; high desert and mountain ranges.', electricityContext: 'Rocky Mountain Power (PacifiCorp) serves most of the state.', policyPosture: 'Net metering in place; Utah has had a state solar tax credit historically.', dsireUrl: 'https://programs.dsireusa.org/system/program/ut', commonQuestions: ['What is the Utah solar tax credit in 2026?', 'How does Rocky Mountain Power net metering work?', 'Are Utah solar incentives available?'] },
  { slug: 'vermont', name: 'Vermont', abbr: 'VT', capital: 'Montpelier', region: 'Northeast', climate: 'Humid continental; long cold winters, mild summers.', electricityContext: 'Green Mountain Power (the dominant utility) plus smaller municipal and co-op utilities.', policyPosture: 'Net metering in place; GMP offers an innovative "bring your own device" battery program.', dsireUrl: 'https://programs.dsireusa.org/system/program/vt', commonQuestions: ['How does Green Mountain Power\'s solar tariff work?', 'Does VT have a solar property tax exemption?', 'What VT solar incentives exist?'] },
  { slug: 'virginia', name: 'Virginia', abbr: 'VA', capital: 'Richmond', region: 'South', climate: 'Humid subtropical; moderate winters, hot summers.', electricityContext: 'Dominion Energy Virginia and Appalachian Power (AEP); cooperative and municipal utilities elsewhere.', policyPosture: 'Virginia Clean Economy Act drives utility solar expansion; net metering capped; shared solar programs exist.', dsireUrl: 'https://programs.dsireusa.org/system/program/va', commonQuestions: ['How does Dominion VA handle rooftop solar?', 'What is the VA shared solar program?', 'Does Virginia have a solar property tax exemption?'] },
  { slug: 'washington', name: 'Washington', abbr: 'WA', capital: 'Olympia', region: 'West', climate: 'Mild, wet in the west; drier in the east; abundant summer sunshine.', electricityContext: 'Puget Sound Energy, Seattle City Light, Tacoma Power, Avista, and PacifiCorp.', policyPosture: 'Net metering in place; state-administered incentive programs vary by utility.', dsireUrl: 'https://programs.dsireusa.org/system/program/wa', commonQuestions: ['How does WA net metering work today?', 'What is PSE\'s solar tariff in 2026?', 'Does WA have a solar property tax exemption?'] },
  { slug: 'west-virginia', name: 'West Virginia', abbr: 'WV', capital: 'Charleston', region: 'South', climate: 'Humid continental; cool to mild summers, cold winters.', electricityContext: 'Appalachian Power and FirstEnergy (Mon Power / Potomac Edison) are major utilities.', policyPosture: 'Modest solar incentives historically; net metering at the state level.', dsireUrl: 'https://programs.dsireusa.org/system/program/wv', commonQuestions: ['Does West Virginia have net metering?', 'What is West Virginia\'s solar property tax treatment?', 'Are WV solar incentives available?'] },
  { slug: 'wisconsin', name: 'Wisconsin', abbr: 'WI', capital: 'Madison', region: 'Midwest', climate: 'Humid continental; cold snowy winters, warm summers.', electricityContext: 'We Energies, Alliant Energy, Madison Gas and Electric, Xcel Energy, plus rural co-ops.', policyPosture: 'Net metering at the state level; Focus on Energy program offers rebates to participating utilities\' customers.', dsireUrl: 'https://programs.dsireusa.org/system/program/wi', commonQuestions: ['What is Focus on Energy\'s solar rebate?', 'How does We Energies net metering work?', 'Does WI have a solar property tax exemption?'] },
  { slug: 'wyoming', name: 'Wyoming', abbr: 'WY', capital: 'Cheyenne', region: 'West', climate: 'High-plains and mountain; cold, dry, windy.', electricityContext: 'Rocky Mountain Power (PacofiCorp) and investor-owned utilities plus rural electric cooperatives.', policyPosture: 'Modest solar incentives; net metering at the state level.', dsireUrl: 'https://programs.dsireusa.org/system/program/wy', commonQuestions: ['What is Wyoming\'s net metering policy?', 'Does WY have a solar property tax exemption?', 'Are WY solar incentives available?'] },
];

export function stateBySlug(slug: string): StatePageContent | undefined {
  return states.find((s) => s.slug === slug);
}
